version: "3.9"

networks:
  cars-service-network:
    driver: bridge

volumes:
  db-data:

services:
  dev-db:
    image: postgres:16
    container_name: dev-db
    networks:
      - cars-service-network
    environment:
      POSTGRES_DB: cars-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  dev-backend:
    build:
      context: /root/dev/Backend.CarService
    image: dev-backend
    container_name: dev-backend
    networks:
      - cars-service-network
    environment:
      ASPNETCORE_ENVIRONMENT: Dev
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - dev-db

  dev-frontend:
    build:
      context: /root/dev/cars-service-ui
      args:
        VITE_MODE: dev
    image: dev-frontend
    container_name: dev-frontend
    networks:
      - cars-service-network
    depends_on:
      - dev-backend